import {
  CliHarness,
  cliLabel,
  cliResumeCommand,
  cliSessionArgument,
  errorMessage,
  HARNESSES,
  type CliSession,
  type CliSessionList,
  type ImportCliSessionInput,
} from "@meldshell/contracts"
import type { RunScript } from "@meldshell/contracts/ipc"
import { Effect } from "effect"
import { CoreClient } from "./core-client"
import { scopePath } from "./thread-worktrees"
import { providerFor } from "./worker-provider"

/*
 * Sessions started in the Claude Code, Codex, Cursor and Pi CLIs come in as threads, and a thread goes back
 * out to its harness's CLI in the thread's terminal.
 */

const CLI_HARNESSES = CliHarness.literals

/** One harness's stored sessions for the folder, each marked with the thread already holding it. */
const harnessSessions = (harness: CliHarness, workspacePath: string) =>
  Effect.gen(function* () {
    const provider = yield* providerFor(harness)
    const status = yield* provider.status
    // A harness that is not installed has stored no sessions worth mentioning.
    if (status.availability === "missing") return { sessions: [], problem: null }
    const summaries = yield* provider.sessions(workspacePath)
    const core = yield* CoreClient
    const held = new Map(
      (yield* core.FindSessionThreads({
        harness,
        nativeThreadIds: summaries.map((summary) => summary.nativeThreadId),
      })).map((entry) => [entry.nativeThreadId, entry.threadId]),
    )
    return {
      sessions: summaries.map(
        (summary): CliSession => ({
          ...summary,
          harness,
          threadId: held.get(summary.nativeThreadId) ?? null,
        }),
      ),
      problem: null,
    }
  }).pipe(
    Effect.catch((cause) =>
      Effect.succeed({
        sessions: [] as CliSession[],
        problem: `${HARNESSES[harness].label} sessions could not be read: ${errorMessage(cause)}`,
      }),
    ),
  )

/** The sessions each harness's CLI stored for a workspace's folder, newest first. */
export const listCliSessions = (workspaceId: string) =>
  Effect.gen(function* () {
    const workspacePath = yield* scopePath({ workspaceId })
    const results = yield* Effect.forEach(
      CLI_HARNESSES,
      (harness) => harnessSessions(harness, workspacePath),
      { concurrency: "unbounded" },
    )
    return {
      sessions: results
        .flatMap((result) => result.sessions)
        .sort((a, b) => b.updatedAt.localeCompare(a.updatedAt)),
      problems: results.flatMap((result) => (result.problem === null ? [] : [result.problem])),
    } satisfies CliSessionList
  })

export const importCliSession = (input: ImportCliSessionInput) =>
  Effect.gen(function* () {
    const workspacePath = yield* scopePath({ workspaceId: input.workspaceId })
    const provider = yield* providerFor(input.harness)
    const history = yield* provider.sessionHistory(workspacePath, input.nativeThreadId)
    const core = yield* CoreClient
    return yield* core.ImportCliSession({ ...input, history })
  })

/** Session IDs are generated by the harness; anything else is never typed into a shell. */
const SAFE_SESSION_ID = /^[\w.-]+$/

/** The CLI command that continues a thread's session, run in the thread's own folder. */
export const cliResumeScript = (threadId: string) =>
  Effect.gen(function* () {
    const core = yield* CoreClient
    const location = yield* core.GetThreadLocation({ threadId })
    if (location.busy)
      return yield* Effect.fail(
        new Error("Wait for this thread's turn to finish before continuing it in the CLI."),
      )
    const session = yield* core.GetResumableSession({ threadId })
    if (session === null)
      return yield* Effect.fail(
        new Error(
          "This thread has no session its agent's CLI can continue yet. Send a message first.",
        ),
      )
    if (!SAFE_SESSION_ID.test(cliSessionArgument(session.harness, session.nativeThreadId)))
      return yield* Effect.fail(new Error("This thread's session ID cannot be passed to a shell."))
    return {
      name: cliLabel(session.harness),
      command: cliResumeCommand(session.harness, session.nativeThreadId),
    } satisfies RunScript
  })
